# Generated by Django 3.1.7 on 2021-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prLink', models.URLField()),
                ('info', models.TextField(max_length=200)),
                ('prImage', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='personalImg',
            field=models.ImageField(default='https://www.google.com.eg/search?q=placeholder&hl=ar&authuser=0&tbm=isch&sxsrf=ALeKk01DOP5kqrJ08nTy8m1ePg9e3H4sKw%3A1618959191777&source=hp&biw=1829&bih=923&ei=V1t_YMuTLdKulwTkoYmQAg&oq=pla&gs_lcp=CgNpbWcQAxgAMgQIIxAnMgIIADICCAAyAggAMgUIABCxAzICCAAyAggAMgUIABCxAzICCAAyAggAOgcIIxDqAhAnUPwFWJMSYMwoaAFwAHgAgAF-iAG_A5IBAzAuNJgBAKABAaoBC2d3cy13aXotaW1nsAEK&sclient=img#imgrc=q1IkN7lSgxq0LM', upload_to='portfolioPage/static'),
        ),
    ]
