# Generated by Django 3.1.7 on 2021-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioPage', '0002_auto_20210424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='personalImg',
            field=models.URLField(),
        ),
    ]
